/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author padil
 * Nama     : Fadhil Gani
 * NPM      : 237006082
 * Kelas    : C
 */
import java.awt.CardLayout;

public class PenampilGambar extends javax.swing.JFrame {

    /**
     * Creates new form PenampilGambar
     */
    public PenampilGambar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JOptionPane = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        GlassFishLabel1 = new javax.swing.JLabel();
        GlassFishLabel2 = new javax.swing.JLabel();
        GlassFishLabel = new javax.swing.JLabel();
        GlassFishButton = new javax.swing.JButton();
        JavaButton = new javax.swing.JButton();
        PostgreButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama: Fadhil Gani");

        jLabel2.setText("NPM: 237006082");

        jLabel3.setText("Kelas: C");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)))
        );

        jPanel2.setLayout(new java.awt.CardLayout());

        GlassFishLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GlassFishLabel1.setIcon(new javax.swing.ImageIcon("/home/padil/Desktop/pbo/PenampilGambar/assets/javaEE.jpg")); // NOI18N
        jPanel2.add(GlassFishLabel1, "1");

        GlassFishLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GlassFishLabel2.setIcon(new javax.swing.ImageIcon("/home/padil/Desktop/pbo/PenampilGambar/assets/postgre.jpg")); // NOI18N
        jPanel2.add(GlassFishLabel2, "2");

        GlassFishLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GlassFishLabel.setIcon(new javax.swing.ImageIcon("/home/padil/Desktop/pbo/PenampilGambar/assets/glassfish.jpg")); // NOI18N
        jPanel2.add(GlassFishLabel, "0");

        GlassFishButton.setText("GlassFish");
        GlassFishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GlassFishButtonActionPerformed(evt);
            }
        });

        JavaButton.setText("JavaEE");
        JavaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JavaButtonActionPerformed(evt);
            }
        });

        PostgreButton.setText("PostgreSQL");
        PostgreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostgreButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GlassFishButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JavaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PostgreButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExitButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GlassFishButton)
                    .addComponent(JavaButton)
                    .addComponent(PostgreButton)
                    .addComponent(ExitButton))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GlassFishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GlassFishButtonActionPerformed
        // TODO add your handling code here:

        /*
         * Nama     : Fadhil Gani
         * NPM      : 237006082
         * Kelas    : C
         */
        CardLayout cl = (CardLayout) (jPanel2.getLayout());
        cl.show(jPanel2, "0");
    }//GEN-LAST:event_GlassFishButtonActionPerformed

    private void JavaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JavaButtonActionPerformed
        // TODO add your handling code here:

        /*
         * Nama     : Fadhil Gani
         * NPM      : 237006082
         * Kelas    : C
         */
        CardLayout cl = (CardLayout) (jPanel2.getLayout());
        cl.show(jPanel2, "1");
    }//GEN-LAST:event_JavaButtonActionPerformed

    private void PostgreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostgreButtonActionPerformed
        // TODO add your handling code here:

        /*
         * Nama     : Fadhil Gani
         * NPM      : 237006082
         * Kelas    : C
         */
        CardLayout cl = (CardLayout) (jPanel2.getLayout());
        cl.show(jPanel2, "2");
    }//GEN-LAST:event_PostgreButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:

        int response = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin keluar?", "Konfirmasi Keluar",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenampilGambar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton GlassFishButton;
    private javax.swing.JLabel GlassFishLabel;
    private javax.swing.JLabel GlassFishLabel1;
    private javax.swing.JLabel GlassFishLabel2;
    private javax.swing.JOptionPane JOptionPane;
    private javax.swing.JButton JavaButton;
    private javax.swing.JButton PostgreButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
